export const rankingData = {
  infoCards: [
    {
      label: "National Rank",
      value: "#8",
      sub: "Out of 36 states/UTs",
      icon: "trophy",
    },
    {
      label: "Overall NIRI Score",
      value: "78.2",
      sub: "-1 from last quarter",
      icon: "score",
    },
    {
      label: "Best Category",
      value: "79",
      sub: "Infrastructure Financing",
      icon: "category",
    },
    {
      label: "Score Gap",
      value: "-9.3",
      sub: "From top performer",
      icon: "gap",
    },
  ],
  categories: [
    {
      name: "Leaders",
      range: ">600 points",
      description: "Top performing states in infrastructure readiness",
      color: "#E6F0FF",
      icon: "leaders",
    },
    {
      name: "Performers",
      range: "400-600 points",
      description: "Well-performing states with good infrastructure",
      color: "#E6F9F0",
      icon: "performers",
    },
    {
      name: "Challengers",
      range: "200-400 points",
      description: "States making steady progress in development",
      color: "#F3E6FF",
      icon: "challengers",
    },
    {
      name: "Strivers",
      range: "<200 points",
      description: "Well-performing states with good infrastructure",
      color: "#FFF3E6",
      icon: "strivers",
    },
  ],
  states: [
    {
      id: 1,
      name: "Maharashtra",
      isUserState: true,
      totalScore: 548,
      financing: 140,
      development: 160,
      ppp: 120,
      enablers: 128,
      category: "Challengers",
      categoryRange: "400-600 pts",
      yoyChange: 2,
      scorePercent: 69.8,
      region: "West",
    },
    {
      id: 2,
      name: "Gujarat",
      totalScore: 742,
      financing: 195,
      development: 230,
      ppp: 195,
      enablers: 195,
      category: "Leaders",
      categoryRange: ">600",
      yoyChange: 2,
      scorePercent: 74.5,
      region: "West",
    },
    {
      id: 3,
      name: "Tamil Nadu",
      totalScore: 698,
      financing: 175,
      development: 210,
      ppp: 165,
      enablers: 148,
      category: "Leaders",
      categoryRange: ">600",
      yoyChange: 2,
      scorePercent: 69.8,
      region: "South",
    },
    {
      id: 4,
      name: "Karnataka",
      totalScore: 685,
      financing: 168,
      development: 205,
      ppp: 172,
      enablers: 140,
      category: "Leaders",
      categoryRange: ">600",
      yoyChange: -2,
      scorePercent: 68.5,
      region: "South",
    },
    {
      id: 5,
      name: "Himachal Pradesh",
      totalScore: 642,
      financing: 155,
      development: 190,
      ppp: 158,
      enablers: 139,
      category: "Leaders",
      categoryRange: ">600",
      yoyChange: 3,
      scorePercent: 64.2,
      region: "North",
    },
    {
      id: 6,
      name: "Uttar Pradesh",
      totalScore: 595,
      financing: 160,
      development: 170,
      ppp: 130,
      enablers: 135,
      category: "Performers",
      categoryRange: "400-600 pts",
      yoyChange: 2,
      scorePercent: 69.8,
      region: "North",
    },
    {
      id: 7,
      name: "Ministry of Defence",
      totalScore: 565,
      financing: 150,
      development: 160,
      ppp: 125,
      enablers: 130,
      category: "Performers",
      categoryRange: "400-600 pts",
      yoyChange: 2,
      scorePercent: 69.8,
      region: "Central",
    },
    // ...add more states as needed for pagination
  ],
  benchmarking: {
    vsTopPerformer: {
      label: "Vs. Top Performer",
      performer: "Gujarat",
      value: "-9.3 points",
      description: "Focus on PPP development to close the gap",
      color: "red",
    },
    vsAllStates: {
      label: "Vs. Top Performer",
      performer: "All States",
      value: "+5.9 points",
      description: "Above average, maintain current trajectory",
      color: "green",
    },
    vsPrevQuarter: {
      label: "Vs. Previous Quarter",
      performer: "Q3 2024",
      value: "-0.6 points",
      description: "Slight decline, need improvement focus",
      color: "red",
    },
  },
  methodology: {
    description:
      "The National Infrastructure Readiness Index evaluates States/UTs across four key pillars, each worth 250 points for a total of 1000 points. The assessment focuses on enabling frameworks rather than just infrastructure outcomes.",
    pillars: [
      {
        name: "Infra Financing",
        points: 250,
        details:
          "Capital allocation, utilization, credit ratings, bond issuances, financial intermediaries.",
      },
      {
        name: "Infra Development",
        points: 250,
        details:
          "Policies, Specialized entities, sector plans, project pipelines, asset monetization.",
      },
      {
        name: "PPP Development",
        points: 250,
        details:
          "PPP policies, functional cells, VGF proposals, Proportion of bankable projects.",
      },
      {
        name: "Infra Enablers",
        points: 250,
        details:
          "NIP portal usage, PMG adoption, GatiShakti planning, dispute resolution, innovations.",
      },
    ],
    note:
      "NIRI aims to encourage competition among states/UTs by highlighting strengths and weaknesses in infrastructure facilitative ecosystems supporting standardized policy-making strategies.",
    period:
      "Assessment Period: Financial Year 2023-24 | Infrastructure sectors as per latest DEA HML notification.",
  },
};
