/**
 * Formal NIE-I indicator definitions (State portal).
 * Shown below each indicator heading in SectionCard; tooltips carry data/scoring details only.
 */

export const INDICATOR_DEFINITIONS: Record<string, string> = {
  "1.1":
    "Percentage of Capex to GSDP measures the share of a state's total capital expenditure relative to its Gross State Domestic Product, indicating the scale of public investment in infrastructure and long-term assets, compared to the size of the state economy. Indicator will be calculated as the ratio of Budgeted Capital Allocation by State in the financial year of assessment and the most recent verifiable GSDP data available.",
  "1.2":
    "Percentage of Capex Utilization measures the proportion of the budgeted capital expenditure that has actually been spent during a given financial period, indicating the efficiency of capital budget implementation. The indicator is calculated as the ratio of actual Capital Expenditure and the Total Budgeted Capital Allocation by the State in the financial year of assessment.",
  "1.3":
    "Percentage of Credit-rated ULBs measures the share of Urban Local Bodies in a State that have obtained a formal credit rating from an accredited agency, indicating their readiness to access market-based financing. The indicator is calculated as the ratio of the number of credit rated ULBs / Total number of ULBs with a population coverage of 50,000 and above, in the financial year of assessment.",
  "1.4":
    "Percentage of ULBs issuing bonds measures the share of Urban Local Bodies that have raised funds through municipal bond issuances, indicating the extent of market-based financing adopted by city governments (No. of ULBs issuing bonds/total no. of ULBs). Under this indicator, issuance of Municipal Bonds, Green Bonds, or any capital market debt instrument in the financial year of assessment would be considered by those ULBs which have a population coverage of 50,000 and above.",
  "1.5":
    "Functional financial intermediary for infra development means any financing entity (statutory body, corporation, trust, etc.) of the State government that mobilizes, structures and channels financing towards infrastructure projects only. SPVs formed only for implementation of a particular project will not be considered under this indicator.",
  "2.1":
    "Availability of Infrastructure Act/Policy refers to the existence of a formal state-level legal or policy framework that guides the planning, financing, and implementation of infrastructure projects within a state. This indicates that an overarching Infrastructure Act/Policy should be available for supporting development of infrastructure projects across multiple sectors. In case no specific infrastructure act or policy is there, sector-specific policies promoting infra in the respective sectors will be accepted, provided the State has a minimum of 3 sector-specific policies for infrastructure. (Infrastructure sectors as per Ministry of Finance's Harmonised Master List or those approved as infra by the State itself).",
  "2.2":
    "Specialized Entity means any state-level Institutional Entity established through Cabinet approval, statute, or Government Order in form of a Authority/Department/Agency, whose primary and exclusive mandate is infrastructure project development, facilitation and structuring across multiple sectors. Statutory Development Authorities, Urban Local Bodies, Industrial or Area Development Authorities, Housing Boards, sector-specific utilities, line departments performing routine administrative functions, or SPVs constituted for a single project, geography, or corridor shall not qualify under this indicator.",
  "2.3":
    "Sector Infrastructure Development Plan means a formally approved, sector-specific planning document prepared by the concerned infrastructure department (or a designated nodal infrastructure agency) for a defined medium- to long-term horizon (normally 5–10 years). The plan must include inter alia current status and targets of infra development with quantum of investment required and proposed ways to mobilize such investment to achieve the targets. Broad policy statements or general development plans without quantified targets, investment estimates, and financing pathways shall not qualify.",
  "2.4":
    "Investment ready project pipeline means a publicly available list of infrastructure that is ready for market engagement / for bidding out and where the public authority is seeking an investor or an equity/JV/developmental partner. Projects included must have crossed minimum preparation thresholds (such as preliminary feasibility/DPR and identification of implementation structure). The pipeline shall be hosted on an official state/center government website, be accessible to investors, and include basic project details and timelines.",
  "2.5":
    "An Asset Monetisation Pipeline shall mean a publicly available list of core brownfield infrastructure assets proposed for monetisation through time-bound transfer of usage or revenue rights to the private sector for an upfront and/or periodic consideration, without transfer of asset ownership. The pipeline shall specify the mode of monetization of the brownfield assets (e.g., TOT, lease, concession, InvIT, O&M with revenue share), indicative timelines, and basic asset details. The pipeline shall be hosted on an official government website and accessible to investors.",
  "3.1":
    "Availability of PPP Act/Policy refers to the existence of a formal legal or policy at State-level that governs the identification, structuring, procurement, and management of Public-Private Partnership (PPP) projects within a state. PPP Policy should be available for supporting development of infrastructure projects in PPP across multiple sectors. It could be either a standalone Policy or a part of the Infrastructure Act/Policy, provided that in such case it clearly specifies provisions for promoting/developing PPP projects.",
  "3.2":
    "Functional State/UT PPP Cell/Unit refers to the presence of an operational institutional unit within the government responsible for supporting PPP project development, appraisal, coordination, and implementation. For the purpose of this indicator, it can either be a standalone entity setup for promoting/undertaking PPP mode of infra project development or a part of Specialized Entity specified in Indicator 2.2 if the entity's mandate clearly specifies provisions for promoting/undertaking PPP projects.",
  "3.3":
    "Proposals Submitted under VGF/IIPDF measures the number or share of infrastructure project proposals that have been submitted for support under the Viability Gap Funding (VGF) or India Infrastructure Project Development Fund (IIPDF) schemes, indicating active efforts to develop PPP projects. Proposals submitted for VGF or Project Development support to either DEA in stipulated format or under a State-Specific Scheme in financial year of assessment will be considered. If the project is being considered under a state scheme, the policy document for the scheme should also be attached.",
  "3.4":
    "TPC of PPP Projects as a Percentage of Total Budgeted Capital Allocation of the State measures the ratio of Total Project Cost (TPC) of PPP projects awarded during the financial year of assessment to the State's annual budgeted capital allocation. This metric indicates the extent to which the State is leveraging private capital and non-budgetary resources to supplement public infrastructure investment, rather than relying solely on budgetary funding.",
  "4.1":
    "This indicator measures whether the State/UT has an operational digital platform to track and monitor infrastructure projects, similar to Government of India's Project Monitoring Group (PMG), enabling real-time review, coordination, and resolution of implementation issues. The portal should enable project-wise, milestone-based monitoring, identification of inter-departmental issues, and monitoring through a defined escalation mechanism, with reviews at highest levels of government.",
  "4.2":
    "Adoption of PM GatiShakti National Master Plan in infrastructure planning means use of PM GatiShakti digital platform and its data layers for project identification and planning stages to inform project alignment, inter-sectoral coordination, and optimisation of project scope and location. Evidence of adoption shall include project-specific use of the platform, such as screenshots of the PM GatiShakti planning interface, State-level dashboards linked to PM GatiShakti, official communications, or project IDs generated on the PM GatiShakti platform. Generic references to PM GatiShakti in policy documents without demonstrable project-level usage shall not qualify.",
  "4.3":
    "Alternative Dispute Resolution (ADR) means any State/UT-notified or contractually mandated mechanism for time-bound resolution of disputes arising from infrastructure or PPP projects, prior to or in lieu of litigation. ADR may include arbitration, conciliation, mediation, dispute resolution boards, or judicial settlement mechanisms (including Lok Adalats or notified settlement schemes), provided these are explicitly applicable to infrastructure contracts. Generic legal provisions or ad-hoc schemes not linked to infrastructure projects shall not qualify.",
  "4.4":
    "The indicator 'Innovative Practice Undertaken for Promotion or Development of Infrastructure' captures the adoption of new institutional, financial, technological, or policy approaches introduced by the State/UT to accelerate infrastructure development or improve project delivery. Innovative practice must be other than those covered under NIE-I metrics. The purpose of the innovative practice shall be including but not limited to encouraging bankable and viable project structuring, faster rolling out of projects, promoting private investment in Infra, promoting user pay models, and efficient project monitoring, etc.",
  "4.5":
    "Capacity Building indicator measures the extent to which government officials have participated in structured training or capacity-building programs related to infrastructure planning, financing, project management, or PPP implementation. For the purpose of this indicator, trainings can be imparted by any source: GoI, State, academic institutes, international agencies, etc.",
  "4.6":
    "Capacity Building indicator measures the extent to which government officials have participated in structured training or capacity-building programs related to infrastructure planning, financing, project management, or PPP implementation. For the purpose of this indicator, trainings can be imparted by any source: GoI, State, academic institutes, international agencies, etc.",
};

export function getIndicatorDefinition(indicatorCode: string): string | null {
  return INDICATOR_DEFINITIONS[indicatorCode] ?? null;
}
